# Generated by Django 4.2.1 on 2023-05-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
        migrations.AddField(
            model_name='seat',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
